server:
   port: 8091
   servlet:
    contextPath: /consumer

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  application:
     name: consumer
  datasource:
        url: jdbc:postgresql://localhost:5432/consumer
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 123456   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
          ddl-auto: create-drop